name: e2e tests

on:
  workflow_dispatch:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"

permissions:
  contents: read

jobs:
  e2e_test:
    name: Run the e2e tests
    runs-on: [self-hosted, Linux, X64, hmpps-github-actions-runner]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # Repository is specified to run the workflow from the API repository
          repository: 'ministryofjustice/hmpps-community-payback-supervisors-ui'

      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: ${{ inputs.node_version_file }}
          cache: npm

      - name: install dependencies
        shell: bash
        run: |
          npm run setup

      - name: install playwright
        shell: bash
        run: |
          npx playwright install

      - name: run e2e tests
        env:
          DELIUS_USERNAME: ${{ secrets.DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.DELIUS_PASSWORD }}
          SUPERVISOR_USERNAME: ${{ secrets.SUPERVISOR_USERNAME }}
          SUPERVISOR_PASSWORD: ${{ secrets.SUPERVISOR_PASSWORD }}
          DELIUS_URL: ${{ vars.DELIUS_URL }}
        shell: bash
        run: |
          npm run test:e2e

      - name: upload results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: npm_e2e_test_artifacts_supervisors_ui
          path: |
            e2e-tests/test_results/
            e2e-tests/playwright-report/

  e2e_test_notify_slack:
    name: "E2E test failure notification"
    needs: e2e_test
    if: ${{ always() && needs.e2e_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ministryofjustice/hmpps-community-payback-ui/.github/actions/slack_failure_notification@9994fccd44456f4b2644908d408478d7c0792264 # main
        with:
          title: "Community Payback Supervisor E2E Tests"
          job: "e2e_test"
          channel_id: ${{ vars.NONPROD_RELEASES_SLACK_CHANNEL }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
